version: "3"
services:
  mysql:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yam
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=yam
    ports:
      - 33060:3306
    volumes:
      - ./db_data/mysql:/var/lib/mysql
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=yam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yam
    ports:
      - 54320:5432
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
  youtube_audio_matcher:
    build:
      context: .
      dockerfile: ./docker/youtube_audio_matcher/Dockerfile
    volumes:
      - ./work:/work
